### ISSUE TITLE
[Feature]: specify namespace on k8sgpt crd

### ISSUE THREAD

**Issue by JuHyung-Son** [k8sgpt-ai/k8sgpt-operator#270]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Problem Description

in k8sgpt crd. there is no namespace selector. so k8sgpt pod analyze all namespaces in cluster
but users may want to specify namespace to watch

### Solution Description

add namespace selector on k8sgpt
and add namespace argument on grpc request
https://github.com/k8sgpt-ai/k8sgpt-operator/blob/7fedf7c967532a415d7631ed7b7399c5dc6dde5a/pkg/client/analysis.go#L18

### Benefits

unnecessary analyzes does not executed

**Comment by singhiqbal1007** [comment]
Hey @AlexsJones, I made a pull request for this at https://github.com/k8sgpt-ai/k8sgpt-operator/pull/291. 
I couldn't join the Slack channel using my email ([singhiqbal1007@gmail.com](mailto:singhiqbal1007@gmail.com)), so I went ahead and created the pull request without discussing the approach since it's a small change. Can you please send me the Slack invite too? Thanks
